name: Run AddressSanitizer

on:
  push:

jobs:
  run-asan:
    name: '${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build pkg-config clang clang-format build-essential curl ccache git zsh
          sudo apt-get install -y libavcodec-dev libavdevice-dev libavfilter-dev libavformat-dev libavutil-dev libswresample-dev libswscale-dev libx264-dev libcurl4-openssl-dev libmbedtls-dev libgl1-mesa-dev libjansson-dev libluajit-5.1-dev python3-dev libx11-dev libxcb-randr0-dev libxcb-shm0-dev libxcb-xinerama0-dev libxcb-composite0-dev libxcomposite-dev libxinerama-dev libxcb1-dev libx11-xcb-dev libxcb-xfixes0-dev swig libcmocka-dev libxss-dev libglvnd-dev libgles2-mesa libgles2-mesa-dev libwayland-dev libsrt-openssl-dev libpci-dev libpipewire-0.3-dev libqrcodegencpp-dev uthash-dev
          sudo apt-get install -y \
                 qt6-base-dev \
                 qt6-base-private-dev \
                 libqt6svg6-dev \
                 qt6-wayland \
                 qt6-image-formats-plugins
          sudo apt-get install -y \
                 libasound2-dev \
                 libfdk-aac-dev \
                 libfontconfig-dev \
                 libfreetype6-dev \
                 libjack-jackd2-dev \
                 libpulse-dev libsndio-dev \
                 libspeexdsp-dev \
                 libudev-dev \
                 libv4l-dev \
                 libva-dev \
                 libvlc-dev \
                 libvpl-dev \
                 libdrm-dev \
                 nlohmann-json3-dev \
                 libwebsocketpp-dev \
                 libasio-dev
      - name: Build repository 
        run: | 
          export CC=clang
          export CXX=clang++
          export CFLAGS="-fsanitize=address -O1 -fno-omit-frame-pointer -fno-common -fsanitize-recover=address -g"
          export LDFLAGS="-fsanitize=address"
          git clone --recursive https://github.com/obsproject/obs-studio.git .
          cmake -S . -B build -G Ninja \
            -DCEF_ROOT_DIR="../obs-build-dependencies/cef_binary_5060_linux_x86_64" \
            -DENABLE_PIPEWIRE=OFF \
            -DENABLE_AJA=0 \
                  -DENABLE_WEBRTC=0 \
            -DQT_VERSION=6 -DENABLE_BROWSER=OFF -DENABLE_NEW_MPEGTS_OUTPUT=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_NATIVE_NVENC=OFF 
          cmake --build build -t libobs

      - name: Install Address Sanitizer dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y clang-14 libclang-14-dev llvm-14 llvm-14-dev llvm-14-tools llvm-14-linker-tools
      
      - name: Run Google Address Sanitizer
        run: |
          set +e

          DIRECTORY=.

          is_executable() {
            local file="$1"
            if file "$file" | grep -q 'ELF 64-bit'; then
              return 0
            else
              return 1
            fi
          }

          run_with_asan() {
            local executable="$1"
            ASAN_OPTIONS="check_initialization_order=true detect_stack_usr_after_return=true print_stats=true atexit=true strict_string_checks=true usr_odr_indicator=true verbosity=2" timeout 10s "$executable"
            local exit_status=$?
          }

          find "$DIRECTORY" -type f -executable | while read -r file; do
            if is_executable "$file"; then
              run_with_asan "$file"
            fi
          done
